name: Build website on Docker
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: yarn install
      
      - name: Build website
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: website
          
