name: Build website on Docker
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: yarn install
      
      - name: Build website
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          # name: website
          # path: website
# But your build command (yarn build) creates the build/ folder, not website/.
          name: build
          path: build
      - name: Test website
        run: |
          yarn global add serve
          apk add --no-cache curl
          serve -s build -l 3000 &
          sleep 10
          curl -f http://localhost:3000 | grep -i "react app"
      - name: Deploy to s3
        uses: docker://amazon/aws-cli:2.28.22
        with:
          entrypoint: ""
        run: |
          aws version
          echo "hello s3" > demo.txt
          aws s3 sync build/ s3://bucket1609san/ --delete
          

          
