name: Build website on Docker
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: yarn install
      
      - name: Build website
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          # name: website
          # path: website
# But your build command (yarn build) creates the build/ folder, not website/.
          name: build
          path: build
      - name: Test website
        run: |
          yarn global add serve
          apk add --no-cache curl
          serve -s build -l 3000 &
          sleep 10
          curl -f http://localhost:3000 | grep -i "react app"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: amazon/aws-cli:2.28.22
      options: "--entrypoint.sh"
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: Deploy to s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        run: |
          aws --version
          aws s3 sync build/ s3://$AWS_S3_BUCKET/ --delete  



          
